
services:

  entity-graph-postgres:
    image: postgres:latest
    container_name: entity_graph_postgres
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: entity_graph_db
      PGDATA: /var/lib/data/postgresql