
server:
  port: 9000
spring:
  application:
    name: entity-graph
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5000/entity_graph_db
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true