
--liquibase formatted sql

--changeset burgasvv:1
create table if not exists task (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    description text not null ,
    created_at timestamp check ( created_at < done_at ),
    done_at timestamp check ( done_at > created_at ),
    done boolean not null
);

--changeset burgasvv:2
begin ;
insert into task(name, description, created_at, done)
values ('Новая задача для разработки 1', 'Описание новой задачи для разработки 1','2025-06-25 10:00', false);
insert into task(name, description, created_at, done)
values ('Новая задача для разработки 2', 'Описание новой задачи для разработки 2','2025-06-26 10:00', false);
insert into task(name, description, created_at, done)
values ('Новая задача для тестирования 1', 'Описание новой задачи для тестирования 1','2025-06-25 10:00', false);
insert into task(name, description, created_at, done)
values ('Новая задача для тестирования 1', 'Описание новой задачи для тестирования 2','2025-06-26 10:00', false);
insert into task(name, description, created_at, done_at, done)
values ('Новая задача для выпуска 1', 'Описание новой задачи для выпуска 1','2025-06-24 15:00', '2025-06-25 18:00', true);
insert into task(name, description, created_at, done)
values ('Новая задача для выпуска 2', 'Описание новой задачи для выпуска 2','2025-06-25 12:00', false);
insert into task(name, description, created_at, done)
values ('Новая задача для выпуска 3', 'Описание новой задачи для выпуска 3','2025-06-25 14:00', false);
commit ;