
--liquibase formatted sql

--changeset burgasvv:1
create table if not exists department (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    description text not null
);

--changeset burgasvv:2
begin ;
insert into department(name, description) values ('Отдел разработки', 'Описание отдела разработки');
insert into department(name, description) values ('Отдел тестирования', 'Описание отдела тестирования');
insert into department(name, description) values ('Отдел выпуска', 'Описание отдела выпуска');
commit ;