
--liquibase formatted sql

--changeset burgasvv:1
create table if not exists employee (
    id bigint generated by default as identity unique not null ,
    name varchar not null ,
    surname varchar not null ,
    patronymic varchar not null ,
    department_id bigint references department(id) on delete set null on update cascade
);

--changeset burgasvv:2
begin ;
insert into employee(name, surname, patronymic, department_id) values ('Игорь','Параев','Константинович',1);
insert into employee(name, surname, patronymic, department_id) values ('Павел','Параев','Константинович',1);
insert into employee(name, surname, patronymic, department_id) values ('Оксана','Кроева','Филиповна',2);
insert into employee(name, surname, patronymic, department_id) values ('Кристина','Сузова','Аркадьевна',2);
insert into employee(name, surname, patronymic, department_id) values ('Владимир','Стрегоев','Михайлович',3);
commit ;